name: 'logsight-setup-action'
description: 'Login, create application, and start log collection'
inputs:
  username:
    description: 'Basic auth username.'
    required: true
  password:
    description: 'Basic auth password.'
    required: true
  application_name:
    description: 'Application name.'
    required: false
    default: ${{ github.ref }}
  tag:
    description: 'Tag that refers to the current version of your software (e.g., {{ $github.sha }})'
    required: false
    default: ${{ github.sha }}
  fluentbit_enable:
    description: 'Flag that enables or disables FluentBit log collection. If disabled, please make sure you have your own input that forwards logs to logsight.ai (https://docs.logsight.ai/#/./send_logs/fluentbit).'
    required: false
    default: 1
  fluentbit_inputname:
    description: 'FluentBit inputs (https://docs.fluentbit.io/manual/pipeline/inputs)'
    required: false
    default: 'tail'
  fluentbit_filelocation:
    description: 'FluentBit file location if using tail as input (https://docs.fluentbit.io/manual/pipeline/inputs/tail)'
    required: false
    default: '/containers/*/*.log'
  fluentbit_matchpattern:
    description: 'FluentBit match pattern. Use * if you want match all messages (https://docs.fluentbit.io/manual/concepts/key-concepts#match)'
    required: false
    default: '*'
  fluentbit_message:
    description: 'FluentBit message string that specifies the Key that contains the log message. (e.g., if using Tail messages automatically have the Key message)'
    required: false
    default: 'message'
  fluentbit_host:
    description: 'Logsight URL. Use logsight.ai for the web service, or 127.0.0.1 for an on-premise solution'
    required: false
    default: 'demo.logsight.ai'
  fluentbit_port:
    description: 'Logsight PORT. Use 443'
    required: false
    default: '443'

outputs:
  application_id:
    description: 'ID of the created application.'
runs:
  using: 'composite'
  steps:
    - uses: actions/logsight-init-action@master
      id: init
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        application-name: ${{ inputs.application_name}}
    - run: $GITHUB_ACTION_PATH/fluentbit_config_generator.sh ${{ inputs.fluentbit_inputname}} ${{ inputs.fluentbit_filelocation}} ${{ inputs.fluentbit_matchpattern}} ${{ steps.init.outputs.application_id}} ${{ github.sha }} ${{ inputs.fluentbit_message}} ${{ inputs.fluentbit_host }} ${{inputs.fluentbit_port}} ${{ inputs.username }} ${{ inputs.password }} > $GITHUB_ACTION_PATH/fluent-bit.conf
      shell: bash
    - run: cat $GITHUB_ACTION_PATH/fluent-bit.conf
      shell: bash
    - run: $GITHUB_ACTION_PATH/docker-compose up -d
      shell: bash
