version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - $GITHUB_ACTION_PATH/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /:/host
    network_mode: "host"
    logging:
      driver: none